---
- :title: The Ruby Programming Language
  :author: 'David Flanagan and Yukihiro Matsumoto '
  :price: '27.13'
  :image_file_name: the-ruby-programming-language.jpg
  :available_on: 2013-12-02
- :title: 'Programming Ruby 1.9 & 2.0: The Pragmatic Programmers'' Guide (The Facets
    of Ruby)'
  :author: 'Dave Thomas, Andy Hunt and Chad Fowler '
  :price: '37.65'
  :image_file_name: programming-ruby-1-9-2-0-the-pragmatic-programmers-guide-the-facets-of-ruby-.jpg
  :available_on: 2013-12-02
- :title: Eloquent Ruby (Addison-Wesley Professional Ruby Series)
  :author: 'Russ Olsen '
  :price: '32.13'
  :image_file_name: eloquent-ruby-addison-wesley-professional-ruby-series-.jpg
  :available_on: 2013-12-02
- :title: 'Ruby Under a Microscope: An Illustrated Guide to Ruby Internals'
  :author: 'Pat Shaughnessy '
  :price: '28.96'
  :image_file_name: ruby-under-a-microscope-an-illustrated-guide-to-ruby-internals.jpg
  :available_on: 2013-12-02
- :title: Computer Science Programming Basics in Ruby
  :author: 'Ophir Frieder, Gideon Frieder and David Grossman '
  :price: '22.49'
  :image_file_name: computer-science-programming-basics-in-ruby.jpg
  :available_on: 2013-12-02
- :title: 'Practical Object-Oriented Design in Ruby: An Agile Primer (Addison-Wesley
    Professional Ruby Series)'
  :author: 'Sandi Metz '
  :price: '29.96'
  :image_file_name: practical-object-oriented-design-in-ruby-an-agile-primer-addison-wesley-professional-ruby-series-.jpg
  :available_on: 2013-12-02
- :title: 'Beginning Ruby: From Novice to Professional (Expert''s Voice in Open Source)'
  :author: 'Peter Cooper '
  :price: '26.05'
  :image_file_name: beginning-ruby-from-novice-to-professional-expert-s-voice-in-open-source-.jpg
  :available_on: 2013-12-02
- :title: Learn to Program, Second Edition (The Facets of Ruby Series)
  :author: 'Chris Pine '
  :price: '17.88'
  :image_file_name: learn-to-program-second-edition-the-facets-of-ruby-series-.jpg
  :available_on: 2013-12-02
- :title: The Ruby Programming Language
  :author: 'David Flanagan and Yukihiro Matsumoto '
  :price: '27.13'
  :image_file_name: the-ruby-programming-language.jpg
  :available_on: 2013-12-02
- :title: 'Programming Ruby 1.9 & 2.0: The Pragmatic Programmers'' Guide (The Facets
    of Ruby)'
  :author: 'Dave Thomas, Andy Hunt and Chad Fowler '
  :price: '37.65'
  :image_file_name: programming-ruby-1-9-2-0-the-pragmatic-programmers-guide-the-facets-of-ruby-.jpg
  :available_on: 2013-12-02
- :title: Eloquent Ruby (Addison-Wesley Professional Ruby Series)
  :author: 'Russ Olsen '
  :price: '32.13'
  :image_file_name: eloquent-ruby-addison-wesley-professional-ruby-series-.jpg
  :available_on: 2013-12-02
- :title: 'Ruby Under a Microscope: An Illustrated Guide to Ruby Internals'
  :author: 'Pat Shaughnessy '
  :price: '28.96'
  :image_file_name: ruby-under-a-microscope-an-illustrated-guide-to-ruby-internals.jpg
  :available_on: 2013-12-02
- :title: Computer Science Programming Basics in Ruby
  :author: 'Ophir Frieder, Gideon Frieder and David Grossman '
  :price: '22.49'
  :image_file_name: computer-science-programming-basics-in-ruby.jpg
  :available_on: 2013-12-02
- :title: 'Practical Object-Oriented Design in Ruby: An Agile Primer (Addison-Wesley
    Professional Ruby Series)'
  :author: 'Sandi Metz '
  :price: '29.96'
  :image_file_name: practical-object-oriented-design-in-ruby-an-agile-primer-addison-wesley-professional-ruby-series-.jpg
  :available_on: 2013-12-02
- :title: 'Beginning Ruby: From Novice to Professional (Expert''s Voice in Open Source)'
  :author: 'Peter Cooper '
  :price: '26.05'
  :image_file_name: beginning-ruby-from-novice-to-professional-expert-s-voice-in-open-source-.jpg
  :available_on: 2013-12-02
- :title: Learn to Program, Second Edition (The Facets of Ruby Series)
  :author: 'Chris Pine '
  :price: '17.88'
  :image_file_name: learn-to-program-second-edition-the-facets-of-ruby-series-.jpg
  :available_on: 2013-12-02
- :title: The Ruby Programming Language
  :author: 'David Flanagan and Yukihiro Matsumoto '
  :price: '27.13'
  :image_file_name: the-ruby-programming-language.jpg
  :available_on: 2013-12-02
- :title: 'Programming Ruby 1.9 & 2.0: The Pragmatic Programmers'' Guide (The Facets
    of Ruby)'
  :author: 'Dave Thomas, Andy Hunt and Chad Fowler '
  :price: '37.65'
  :image_file_name: programming-ruby-1-9-2-0-the-pragmatic-programmers-guide-the-facets-of-ruby-.jpg
  :available_on: 2013-12-02
- :title: Eloquent Ruby (Addison-Wesley Professional Ruby Series)
  :author: 'Russ Olsen '
  :price: '32.13'
  :image_file_name: eloquent-ruby-addison-wesley-professional-ruby-series-.jpg
  :available_on: 2013-12-02
- :title: 'Ruby Under a Microscope: An Illustrated Guide to Ruby Internals'
  :author: 'Pat Shaughnessy '
  :price: '28.96'
  :image_file_name: ruby-under-a-microscope-an-illustrated-guide-to-ruby-internals.jpg
  :available_on: 2013-12-02
- :title: Computer Science Programming Basics in Ruby
  :author: 'Ophir Frieder, Gideon Frieder and David Grossman '
  :price: '22.49'
  :image_file_name: computer-science-programming-basics-in-ruby.jpg
  :available_on: 2013-12-02
- :title: 'Practical Object-Oriented Design in Ruby: An Agile Primer (Addison-Wesley
    Professional Ruby Series)'
  :author: 'Sandi Metz '
  :price: '29.96'
  :image_file_name: practical-object-oriented-design-in-ruby-an-agile-primer-addison-wesley-professional-ruby-series-.jpg
  :available_on: 2013-12-02
- :title: 'Beginning Ruby: From Novice to Professional (Expert''s Voice in Open Source)'
  :author: 'Peter Cooper '
  :price: '26.05'
  :image_file_name: beginning-ruby-from-novice-to-professional-expert-s-voice-in-open-source-.jpg
  :available_on: 2013-12-02
- :title: Learn to Program, Second Edition (The Facets of Ruby Series)
  :author: 'Chris Pine '
  :price: '17.88'
  :image_file_name: learn-to-program-second-edition-the-facets-of-ruby-series-.jpg
  :available_on: 2013-12-02
