---
- :price: "23.75"
  :author: "David Flanagan and Yukihiro Matsumoto "
  :title: The Ruby Programming Language
  :image_file_name: the-ruby-programming-language.jpg
  :featured: true
  :available_on: 2011-02-16
- :price: "28.20"
  :author: "Dave Thomas, Chad Fowler,  and Andy Hunt "
  :title: "Programming Ruby 1.9: The Pragmatic Programmers' Guide (Facets of Ruby)"
  :image_file_name: programming-ruby-1-9-the-pragmatic-programmers-guide-facets-of-ruby-.jpg
  :featured: true
  :available_on: 2011-02-16
- :price: "22.61"
  :author: "Peter Cooper "
  :title: "Beginning Ruby: From Novice to Professional"
  :image_file_name: beginning-ruby-from-novice-to-professional.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "20.50"
  :author: "Paolo Perrotta "
  :title: "Metaprogramming Ruby: Program Like the Ruby Pros"
  :image_file_name: metaprogramming-ruby-program-like-the-ruby-pros.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "27.99"
  :author: "David A. Black "
  :title: The Well-Grounded Rubyist
  :image_file_name: the-well-grounded-rubyist.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "31.17"
  :author: "Lucas Carlson and Leonard Richardson "
  :title: Ruby Cookbook (Cookbooks (O'Reilly))
  :image_file_name: ruby-cookbook-cookbooks-o-reilly-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "13.92"
  :author: "Chris Pine "
  :title: Learn to Program, Second Edition (The Facets of Ruby Series)
  :image_file_name: learn-to-program-second-edition-the-facets-of-ruby-series-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "22.85"
  :author: "Michael James Fitzgerald "
  :title: Learning Ruby
  :image_file_name: learning-ruby.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "23.07"
  :author: "Bruce Tate "
  :title: "Seven Languages in Seven Weeks: A Pragmatic Guide to Learning Programming Languages (Pragmatic Programmers)"
  :image_file_name: seven-languages-in-seven-weeks-a-pragmatic-guide-to-learning-programming-languages-pragmatic-programmers-.jpg
  :featured: true
  :available_on: 2011-02-16
- :price: "9.99"
  :author: "Neil Smyth "
  :title: Ruby Programming Essentials
  :image_file_name: ruby-programming-essentials.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "28.21"
  :author: "Russ Olsen "
  :title: Eloquent Ruby (Addison-Wesley Professional Ruby Series)
  :image_file_name: eloquent-ruby-addison-wesley-professional-ruby-series-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "23.75"
  :author: "David Flanagan and Yukihiro Matsumoto "
  :title: The Ruby Programming Language
  :image_file_name: the-ruby-programming-language.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "28.20"
  :author: "Dave Thomas, Chad Fowler,  and Andy Hunt "
  :title: "Programming Ruby 1.9: The Pragmatic Programmers' Guide (Facets of Ruby)"
  :image_file_name: programming-ruby-1-9-the-pragmatic-programmers-guide-facets-of-ruby-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "22.61"
  :author: "Peter Cooper "
  :title: "Beginning Ruby: From Novice to Professional"
  :image_file_name: beginning-ruby-from-novice-to-professional.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "20.50"
  :author: "Paolo Perrotta "
  :title: "Metaprogramming Ruby: Program Like the Ruby Pros"
  :image_file_name: metaprogramming-ruby-program-like-the-ruby-pros.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "27.99"
  :author: "David A. Black "
  :title: The Well-Grounded Rubyist
  :image_file_name: the-well-grounded-rubyist.jpg
  :featured: true
  :available_on: 2011-02-16
- :price: "31.17"
  :author: "Lucas Carlson and Leonard Richardson "
  :title: Ruby Cookbook (Cookbooks (O'Reilly))
  :image_file_name: ruby-cookbook-cookbooks-o-reilly-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "13.92"
  :author: "Chris Pine "
  :title: Learn to Program, Second Edition (The Facets of Ruby Series)
  :image_file_name: learn-to-program-second-edition-the-facets-of-ruby-series-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "22.85"
  :author: "Michael James Fitzgerald "
  :title: Learning Ruby
  :image_file_name: learning-ruby.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "23.07"
  :author: "Bruce Tate "
  :title: "Seven Languages in Seven Weeks: A Pragmatic Guide to Learning Programming Languages (Pragmatic Programmers)"
  :image_file_name: seven-languages-in-seven-weeks-a-pragmatic-guide-to-learning-programming-languages-pragmatic-programmers-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "9.99"
  :author: "Neil Smyth "
  :title: Ruby Programming Essentials
  :image_file_name: ruby-programming-essentials.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "28.21"
  :author: "Russ Olsen "
  :title: Eloquent Ruby (Addison-Wesley Professional Ruby Series)
  :image_file_name: eloquent-ruby-addison-wesley-professional-ruby-series-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "23.75"
  :author: "David Flanagan and Yukihiro Matsumoto "
  :title: The Ruby Programming Language
  :image_file_name: the-ruby-programming-language.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "28.20"
  :author: "Dave Thomas, Chad Fowler,  and Andy Hunt "
  :title: "Programming Ruby 1.9: The Pragmatic Programmers' Guide (Facets of Ruby)"
  :image_file_name: programming-ruby-1-9-the-pragmatic-programmers-guide-facets-of-ruby-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "22.61"
  :author: "Peter Cooper "
  :title: "Beginning Ruby: From Novice to Professional"
  :image_file_name: beginning-ruby-from-novice-to-professional.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "20.50"
  :author: "Paolo Perrotta "
  :title: "Metaprogramming Ruby: Program Like the Ruby Pros"
  :image_file_name: metaprogramming-ruby-program-like-the-ruby-pros.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "27.99"
  :author: "David A. Black "
  :title: The Well-Grounded Rubyist
  :image_file_name: the-well-grounded-rubyist.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "31.17"
  :author: "Lucas Carlson and Leonard Richardson "
  :title: Ruby Cookbook (Cookbooks (O'Reilly))
  :image_file_name: ruby-cookbook-cookbooks-o-reilly-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "13.92"
  :author: "Chris Pine "
  :title: Learn to Program, Second Edition (The Facets of Ruby Series)
  :image_file_name: learn-to-program-second-edition-the-facets-of-ruby-series-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "22.85"
  :author: "Michael James Fitzgerald "
  :title: Learning Ruby
  :image_file_name: learning-ruby.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "23.07"
  :author: "Bruce Tate "
  :title: "Seven Languages in Seven Weeks: A Pragmatic Guide to Learning Programming Languages (Pragmatic Programmers)"
  :image_file_name: seven-languages-in-seven-weeks-a-pragmatic-guide-to-learning-programming-languages-pragmatic-programmers-.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "9.99"
  :author: "Neil Smyth "
  :title: Ruby Programming Essentials
  :image_file_name: ruby-programming-essentials.jpg
  :featured: false
  :available_on: 2011-02-16
- :price: "28.21"
  :author: "Russ Olsen "
  :title: Eloquent Ruby (Addison-Wesley Professional Ruby Series)
  :image_file_name: eloquent-ruby-addison-wesley-professional-ruby-series-.jpg
  :featured: false
  :available_on: 2011-02-16