version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    groups:
      test-dependencies:
        dependency-type: "test"
      rubocop:
        dependency-type: "rubocop"
