---

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  DisabledByDefault: true

  TargetRubyVersion: 3.1
  TargetRailsVersion: 6.0

  Exclude:
    - vendor/bundle/**/*

  DisplayCopNames: true

  StyleGuideCopsOnly: false

Metrics:
  Enabled: false

RSpec/FactoryBot/AttributeDefinedStatically:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
