require:
  - rubocop-rspec
  - rubocop-rails
AllCops:
  DisabledByDefault: true
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.0
  Exclude:
    - .git/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/* # avoid running Rubocop in GHA ruby/setup-ruby on vendored dependencies!
    - .github/**/*
    - public/**/*
    - config/**/*.yml
    - bin/**/*
Metrics:
  Enabled: false

FactoryBot/AttributeDefinedStatically:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
