---

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  DisabledByDefault: true

  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2

  DisplayCopNames: true

  StyleGuideCopsOnly: false

Metrics:
  Enabled: false

FactoryBot/AttributeDefinedStatically:
  Enabled: true
