name: Tests

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  COVERAGE_RETENTION_DAYS: 3

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
        run: bin/rails db:setup test:all
      - name: Upload screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        with:
          name: rails-coverage
          path: coverage
          if-no-files-found: error
          retention-days: ${{ env.COVERAGE_RETENTION_DAYS }}

  upload_coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest
    needs:
      - run_tests
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          name: rails-coverage
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
